'use client';
import {useMemo,useState} from 'react';
import {LayoutDashboard,BookOpen,CalendarDays,BarChart3,Settings,Plus,Search,ChevronDown,ArrowUpRight,ArrowDownRight,MoreHorizontal,X,Image as ImageIcon} from 'lucide-react';

const seed=[
{id:1,date:'2026-08-17',time:'14:32',symbol:'NQ',side:'Long',entry:23318.25,exit:23364.75,qty:2,fees:8.4,setup:'Breakout',strategy:'Opening Range',r:2.1,pnl:457.6,duration:'00:28',notes:'Breakout propre, attente de confirmation.'},
{id:2,date:'2026-08-17',time:'10:14',symbol:'ES',side:'Short',entry:6421.5,exit:6415.25,qty:1,fees:4.2,setup:'Pullback',strategy:'Trend Continuation',r:1.3,pnl:308.3,duration:'00:19',notes:'Retour sur niveau puis rejet.'},
{id:3,date:'2026-08-15',time:'15:08',symbol:'NQ',side:'Long',entry:23102,exit:23068.5,qty:1,fees:4.2,setup:'Reversal',strategy:'Liquidity Sweep',r:-1,pnl:-172.5,duration:'00:11',notes:'Entrée trop tôt.'},
{id:4,date:'2026-08-14',time:'09:47',symbol:'CL',side:'Short',entry:64.22,exit:63.71,qty:2,fees:7.8,setup:'Breakdown',strategy:'Opening Range',r:2.6,pnl:1014.2,duration:'00:36',notes:'Très bon déplacement après cassure.'},
{id:5,date:'2026-08-13',time:'13:21',symbol:'ES',side:'Long',entry:6398.25,exit:6391.75,qty:1,fees:4.2,setup:'Reversal',strategy:'VWAP Reclaim',r:-1,pnl:-329.2,duration:'00:17',notes:'Contexte faible.'},
{id:6,date:'2026-08-12',time:'16:02',symbol:'NQ',side:'Short',entry:22984.5,exit:22926.25,qty:1,fees:4.2,setup:'Pullback',strategy:'Trend Continuation',r:2.2,pnl:578.3,duration:'00:24',notes:'Bon suivi de tendance.'},
{id:7,date:'2026-08-11',time:'11:36',symbol:'GC',side:'Long',entry:3398.1,exit:3405.2,qty:1,fees:4.2,setup:'Breakout',strategy:'Opening Range',r:1.7,pnl:705.8,duration:'00:31',notes:'Momentum propre.'}
];
const money=n=>`${n>=0?'+':''}${n.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})} €`;
const pct=n=>`${n.toFixed(1)}%`;
function Stat({label,value,sub,positive}){return <div className="stat"><div className="muted">{label}</div><div className={'statValue '+(positive===true?'pos':positive===false?'neg':'')}>{value}</div>{sub&&<div className="small muted">{sub}</div>}</div>}
function Nav({page,setPage}){let items=[['Dashboard',LayoutDashboard],['Trades',BookOpen],['Calendar',CalendarDays],['Analytics',BarChart3]];return <aside><div className="brand"><div className="logo">TJ</div><div><b>Trading Journal</b><span>Personal workspace</span></div></div><nav>{items.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/>{n}</button>)}</nav><div className="sideBottom"><button onClick={()=>setPage('Settings')}><Settings size={18}/>Settings</button><div className="user"><div className="avatar">TR</div><div><b>Trader</b><span>Personal account</span></div></div></div></aside>}
function Header({title,onNew}){return <header><div><div className="eyebrow">TRADING JOURNAL</div><h1>{title}</h1></div><button className="primary" onClick={onNew}><Plus size={18}/>New trade</button></header>}
function Dashboard({trades}){const s=useMemo(()=>{let pnl=trades.reduce((a,t)=>a+t.pnl,0), wins=trades.filter(t=>t.pnl>0),loss=trades.filter(t=>t.pnl<0);let grossW=wins.reduce((a,t)=>a+t.pnl,0),grossL=Math.abs(loss.reduce((a,t)=>a+t.pnl,0));return {pnl,wins:wins.length,loss:loss.length,wr:wins.length/trades.length*100,pf:grossL?grossW/grossL:0,avgW:grossW/(wins.length||1),avgL:grossL/(loss.length||1),exp:pnl/trades.length,r:trades.reduce((a,t)=>a+t.r,0)}} , [trades]);
let equity=[];let running=0;[...trades].reverse().forEach(t=>{running+=t.pnl;equity.push({date:t.date.slice(5),v:running})}); equity=equity.reverse(); let max=Math.max(...equity.map(x=>x.v),0);let min=Math.min(...equity.map(x=>x.v),0);return <><div className="stats"><Stat label="Net P&L" value={money(s.pnl)} positive={s.pnl>=0}/><Stat label="Win rate" value={pct(s.wr)} sub={`${s.wins} wins · ${s.loss} losses`}/><Stat label="Profit factor" value={s.pf.toFixed(2)}/><Stat label="Average win" value={money(s.avgW)} positive/><Stat label="Average loss" value={'-'+money(s.avgL).replace('+','')} positive={false}/><Stat label="Expectancy" value={money(s.exp)} positive={s.exp>=0}/></div><div className="grid2"><div className="card chartCard"><div className="cardHead"><div><b>Equity curve</b><span>Accumulated P&L</span></div><button className="ghost">All time <ChevronDown size={15}/></button></div><div className="chart"><svg viewBox="0 0 760 250" preserveAspectRatio="none"><path d={'M 0 220 '+equity.map((p,i)=>`L ${(i/(equity.length-1||1))*760} ${220-((p.v-min)/((max-min)||1))*190}`).join(' ') } fill="none" stroke="currentColor" strokeWidth="3"/><path d={'M 0 220 '+equity.map((p,i)=>`L ${(i/(equity.length-1||1))*760} ${220-((p.v-min)/((max-min)||1))*190}`).join(' ')+' L 760 250 L 0 250 Z'} fill="currentColor" opacity=".08"/></svg><div className="chartLabels"><span>Aug 11</span><span>Aug 17</span></div></div></div><div className="card"><div className="cardHead"><div><b>Performance</b><span>Recent trading days</span></div></div><div className="bars">{equity.map((p,i)=><div className="barRow" key={i}><span>{p.date}</span><div className="barTrack"><div className="bar" style={{width:Math.min(100,Math.max(8,Math.abs(p.v)/(Math.max(max,Math.abs(min))||1)*100))+'%'}}/></div><strong className={p.v>=0?'pos':'neg'}>{money(p.v)}</strong></div>)}</div></div></div><div className="card"><div className="cardHead"><div><b>Recent trades</b><span>Your latest journal entries</span></div></div><TradeTable trades={trades.slice(0,5)}/></div></>}
function TradeTable({trades,onSelect}){return <div className="tableWrap"><table><thead><tr><th>Date</th><th>Symbol</th><th>Side</th><th>Setup</th><th>Entry</th><th>Exit</th><th>R</th><th>P&L</th><th></th></tr></thead><tbody>{trades.map(t=><tr key={t.id} onClick={()=>onSelect?.(t)}><td>{t.date}<span className="small muted"> {t.time}</span></td><td><b>{t.symbol}</b></td><td><span className={'side '+t.side.toLowerCase()}>{t.side==='Long'?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {t.side}</span></td><td>{t.setup}</td><td>{t.entry}</td><td>{t.exit}</td><td className={t.r>=0?'pos':'neg'}>{t.r>0?'+':''}{t.r.toFixed(1)}R</td><td className={t.pnl>=0?'pos':'neg'}><b>{money(t.pnl)}</b></td><td><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div>}
function Trades({trades,setTrades,select}){const [q,setQ]=useState('');const filtered=trades.filter(t=>(t.symbol+t.setup+t.strategy).toLowerCase().includes(q.toLowerCase()));return <div className="card"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search trades..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="ghost">All symbols <ChevronDown size={15}/></button><button className="ghost">All setups <ChevronDown size={15}/></button><button className="ghost">All results <ChevronDown size={15}/></button></div><TradeTable trades={filtered} onSelect={select}/></div>}
function Calendar({trades}){let by={};trades.forEach(t=>by[t.date]=(by[t.date]||0)+t.pnl);return <div className="card"><div className="calendarHead"><button className="ghost">‹</button><b>August 2026</b><button className="ghost">›</button></div><div className="week">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:42},(_,i)=>{let d=i-5;let date=d>0?`2026-08-${String(d).padStart(2,'0')}`:'';let v=by[date];return <div className={'day '+(date?'':'blank')} key={i}><span>{d>0&&d<=31?d:''}</span>{v!==undefined&&<strong className={v>=0?'pos':'neg'}>{money(v)}</strong>}</div>})}</div></div>}
function Analytics({trades}){let group=(key)=>Object.entries(trades.reduce((a,t)=>{let k=t[key];a[k]??={pnl:0,n:0,r:0};a[k].pnl+=t.pnl;a[k].n++;a[k].r+=t.r;return a},{})).sort((a,b)=>b[1].pnl-a[1].pnl);return <div className="grid2"><div className="card"><div className="cardHead"><div><b>By setup</b><span>Where your edge comes from</span></div></div><MiniTable rows={group('setup')}/></div><div className="card"><div className="cardHead"><div><b>By instrument</b><span>Performance by market</span></div></div><MiniTable rows={group('symbol')}/></div><div className="card"><div className="cardHead"><div><b>Long vs Short</b></div></div><MiniTable rows={group('side')}/></div><div className="card"><div className="cardHead"><div><b>By strategy</b></div></div><MiniTable rows={group('strategy')}/></div></div>}
function MiniTable({rows}){return <div className="mini">{rows.map(([k,v])=><div className="miniRow" key={k}><span><b>{k}</b><small>{v.n} trades · {v.r.toFixed(1)}R</small></span><strong className={v.pnl>=0?'pos':'neg'}>{money(v.pnl)}</strong></div>)}</div>}
function Modal({trade,onClose,onSave}){const [form,setForm]=useState(trade||{date:new Date().toISOString().slice(0,10),time:'',symbol:'NQ',side:'Long',entry:'',exit:'',qty:1,fees:0,setup:'Breakout',strategy:'',r:'',pnl:'',duration:'',notes:''});let f=(k,v)=>setForm({...form,[k]:v});return <div className="overlay"><div className="modal"><div className="modalHead"><div><div className="eyebrow">JOURNAL ENTRY</div><h2>{trade?'Trade details':'New trade'}</h2></div><button className="iconBtn" onClick={onClose}><X/></button></div><div className="formGrid">{[['date','Date'],['time','Entry time'],['symbol','Symbol'],['side','Side'],['entry','Entry'],['exit','Exit'],['qty','Quantity'],['fees','Fees'],['setup','Setup'],['strategy','Strategy'],['r','R multiple'],['pnl','P&L'],['duration','Duration']].map(([k,l])=><label key={k}>{l}{k==='side'?<select value={form[k]} onChange={e=>f(k,e.target.value)}><option>Long</option><option>Short</option></select>:<input value={form[k]} onChange={e=>f(k,e.target.value)}/>}</label>)}<label className="full">Notes<textarea value={form.notes} onChange={e=>f('notes',e.target.value)} placeholder="Trade thesis, execution, mistakes, lessons..."/></label><div className="full upload"><ImageIcon size={20}/><div><b>Trade screenshots</b><span>Drop images here or choose files</span></div><button className="ghost">Add image</button></div></div><div className="modalFoot"><button className="ghost" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave({...form,id:trade?.id||Date.now(),entry:Number(form.entry)||0,exit:Number(form.exit)||0,qty:Number(form.qty)||0,fees:Number(form.fees)||0,r:Number(form.r)||0,pnl:Number(form.pnl)||0})}>Save trade</button></div></div></div>}
export default function App(){const [page,setPage]=useState('Dashboard'),[trades,setTrades]=useState(seed),[modal,setModal]=useState(null);let title=page;return <div className="app"><Nav page={page} setPage={setPage}/><main><Header title={title} onNew={()=>setModal('new')}/>{page==='Dashboard'&&<Dashboard trades={trades}/>} {page==='Trades'&&<Trades trades={trades} setTrades={setTrades} select={t=>setModal(t)}/>} {page==='Calendar'&&<Calendar trades={trades}/>} {page==='Analytics'&&<Analytics trades={trades}/>} {page==='Settings'&&<div className="card settings"><h2>Settings</h2><p className="muted">V1 — preferences and account configuration will be connected to the cloud backend.</p></div>}</main>{modal&&<Modal trade={modal==='new'?null:modal} onClose={()=>setModal(null)} onSave={t=>{setTrades(x=>[t,...x.filter(a=>a.id!==t.id)]);setModal(null)}}/>}</div>}
